# Generated by Django 6.1.1 on 2026-10-06 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='show',
            name='poster',
        ),
        migrations.AddField(
            model_name='movie',
            name='poster_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='show',
            name='poster_url',
            field=models.URLField(blank=True),
        ),
    ]
